apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-progressive-role-binding
  labels:
    app.kubernetes.io/component: argocd-progressive-controller
    app.kubernetes.io/name: argocd-progressive-role-binding
    app.kubernetes.io/part-of: argocd-progressive
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-progressive-role
subjects:
- kind: ServiceAccount
  name: argocd-progressive