apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-progressive
  labels:
    app.kubernetes.io/component: argocd-progressive-controller
    app.kubernetes.io/name: argocd-progressive
    app.kubernetes.io/part-of: argocd-progressive